import { NextRequest, NextResponse } from "next/server";
import { getValidAccessToken, applyRefreshedCookie } from "@/lib/auth";
import {
  getUserProfile,
  createPlaylist,
  addTracksToPlaylist,
} from "@/lib/spotify";

export async function POST(request: NextRequest) {
  const tokenResult = await getValidAccessToken(request);
  if (!tokenResult) {
    return NextResponse.json({ error: "Not authenticated" }, { status: 401 });
  }

  try {
    const { trackUris } = (await request.json()) as { trackUris: string[] };

    if (!trackUris || trackUris.length === 0) {
      return NextResponse.json(
        { error: "No tracks provided" },
        { status: 400 }
      );
    }

    const token = tokenResult.access_token;
    const user = await getUserProfile(token);

    const playlist = await createPlaylist(
      token,
      user.id,
      "My Swipe Taste Playlist",
      "Generated by Spotify Swipe - a personalized playlist based on your music taste!"
    );

    await addTracksToPlaylist(token, playlist.id, trackUris);

    const response = NextResponse.json({
      playlistUrl: playlist.external_urls.spotify,
      playlistName: playlist.name,
      trackCount: trackUris.length,
    });
    return applyRefreshedCookie(response, tokenResult);
  } catch (error) {
    console.error("Failed to create playlist:", error);
    return NextResponse.json(
      { error: "Failed to create playlist" },
      { status: 500 }
    );
  }
}
